// src/views/FeedView.tsx
import { useEffect, useRef, useState } from 'react'
import { supabase } from '../lib/supabase'
import type { RealtimeChannel } from '@supabase/supabase-js'
import SkeletonCard from '../components/SkeletonCard'

type FeedRow = { id: number; user_id: string; message: string; created_at: string; avatar_url?: string | null }

function initial(message: string) {
  return (message.match(/^(\S)/)?.[1] ?? '?').toUpperCase()
}

function relTime(iso: string) {
  const diff = Date.now() - new Date(iso).getTime()
  const s = Math.round(diff / 1000)
  if (s < 60) return `${s}s`
  const m = Math.round(s / 60)
  if (m < 60) return `${m}m`
  const h = Math.round(m / 60)
  if (h < 24) return `${h}h`
  return `${Math.round(h / 24)}d`
}

const COLORS = ['#FF6B35', '#00D68F', '#CAFF33', '#818CF8', '#FF4545', '#06b6d4']
function colorFor(userId: string) {
  let h = 0
  for (let i = 0; i < userId.length; i++) h = (h * 31 + userId.charCodeAt(i)) >>> 0
  return COLORS[h % COLORS.length]
}

export default function FeedView() {
  const [events, setEvents] = useState<FeedRow[]>([])
  const [loading, setLoading] = useState(true)
  const avatarMap = useRef(new Map<string, string | null>())
  const channelRef = useRef<RealtimeChannel | null>(null)

  async function load() {
    setLoading(true)
    const { data, error } = await supabase
      .from('feed_event')
      .select('id, user_id, message, created_at, profile:user_id(avatar_url)')
      .order('created_at', { ascending: false })
      .limit(100)
    setLoading(false)
    if (!error && data) {
      const rows = (data as any[]).map((r: any) => ({
        id: r.id, user_id: r.user_id, message: r.message, created_at: r.created_at,
        avatar_url: r.profile?.avatar_url ?? null,
      }))
      setEvents(rows)
      for (const ev of rows) {
        if (!avatarMap.current.has(ev.user_id)) avatarMap.current.set(ev.user_id, ev.avatar_url ?? null)
      }
    }
  }

  useEffect(() => {
    load()
    channelRef.current = supabase.channel('feed')
      .on('postgres_changes', { event: 'INSERT', schema: 'public', table: 'feed_event' }, async (payload) => {
        const raw = payload.new as { id: number; user_id: string; message: string; created_at: string }
        let avatar = avatarMap.current.get(raw.user_id)
        if (avatar === undefined) {
          const { data } = await supabase.from('profile').select('avatar_url').eq('id', raw.user_id).maybeSingle()
          avatar = data?.avatar_url ?? null
          avatarMap.current.set(raw.user_id, avatar)
        }
        setEvents(prev => [{ ...raw, avatar_url: avatar }, ...prev])
      })
      .subscribe()
    return () => { channelRef.current?.unsubscribe() }
  }, [])

  if (loading) return <div><SkeletonCard rows={3} /><SkeletonCard rows={3} /></div>

  return (
    <div>
      {events.length === 0 ? (
        <div className="card" style={{ padding: '3rem 1rem', textAlign: 'center' }}>
          <i className="bi bi-people" style={{ fontSize: '2rem', color: 'var(--muted)' }} />
          <div style={{ marginTop: '.75rem', fontWeight: 700, fontSize: 15, color: 'var(--text)' }}>No activity yet</div>
          <div style={{ fontSize: '.82rem', color: 'var(--text-2)', marginTop: '.25rem' }}>
            Workouts and nutrition milestones appear here.
          </div>
        </div>
      ) : (
        <div className="card fade-up" style={{ overflow: 'hidden' }}>
          {events.map(ev => (
            <div key={ev.id} className="feed-item">
              <div className="feed-avatar" style={{ background: ev.avatar_url ? 'transparent' : colorFor(ev.user_id) }}>
                {ev.avatar_url
                  ? <img src={ev.avatar_url} alt="" />
                  : initial(ev.message)
                }
              </div>
              <div style={{ flex: 1, minWidth: 0 }}>
                <p style={{ fontSize: 14, color: 'var(--text)', lineHeight: 1.4, margin: 0, overflow: 'hidden', display: '-webkit-box', WebkitLineClamp: 2, WebkitBoxOrient: 'vertical' as any }}>
                  {ev.message}
                </p>
                <span className="num" style={{ fontSize: 11, color: 'var(--muted)', marginTop: 4, display: 'block' }}>{relTime(ev.created_at)} ago</span>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  )
}

// src/views/FeedView.vue
<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref } from 'vue'
import { supabase } from '../lib/supabase'
import type { RealtimeChannel } from '@supabase/supabase-js'
import SkeletonCard from '../components/SkeletonCard.vue'

type FeedRow = {
  id: number
  user_id: string
  message: string
  created_at: string
  avatar_url?: string | null
}

const events = ref<FeedRow[]>([])
const loading = ref(true)
const avatarMap = ref<Map<string, string | null>>(new Map())
let channel: RealtimeChannel | null = null

async function load() {
  loading.value = true
  const { data, error } = await supabase
    .from('feed_event')
    .select('id, user_id, message, created_at, profile:user_id(avatar_url)')
    .order('created_at', { ascending: false })
    .limit(100)

  loading.value = false
  if (!error && data) {
    events.value = data.map((r: any) => ({
      id:         r.id,
      user_id:    r.user_id,
      message:    r.message,
      created_at: r.created_at,
      avatar_url: r.profile?.avatar_url ?? null
    }))
    for (const ev of events.value) {
      if (!avatarMap.value.has(ev.user_id)) {
        avatarMap.value.set(ev.user_id, ev.avatar_url ?? null)
      }
    }
  }
}

function subscribe() {
  channel = supabase
    .channel('feed')
    .on(
      'postgres_changes',
      { event: 'INSERT', schema: 'public', table: 'feed_event' },
      async (payload) => {
        const raw = payload.new as { id: number; user_id: string; message: string; created_at: string }
        let avatar = avatarMap.value.get(raw.user_id)
        if (avatar === undefined) {
          const { data } = await supabase
            .from('profile')
            .select('avatar_url')
            .eq('id', raw.user_id)
            .maybeSingle()
          avatar = data?.avatar_url ?? null
          avatarMap.value.set(raw.user_id, avatar)
        }
        events.value.unshift({ ...raw, avatar_url: avatar })
      }
    )
    .subscribe()
}

function initial(message: string): string {
  return (message.match(/^(\S)/)?.[1] ?? '?').toUpperCase()
}

function relTime(iso: string): string {
  const diff = Date.now() - new Date(iso).getTime()
  const s = Math.round(diff / 1000)
  if (s < 60)  return `${s}s ago`
  const m = Math.round(s / 60)
  if (m < 60)  return `${m}m ago`
  const h = Math.round(m / 60)
  if (h < 24)  return `${h}h ago`
  const d = Math.round(h / 24)
  if (d < 7)   return `${d}d ago`
  return new Date(iso).toLocaleDateString()
}

onMounted(() => { load(); subscribe() })
onBeforeUnmount(() => { if (channel) supabase.removeChannel(channel) })
</script>

<template>
  <template v-if="loading">
    <SkeletonCard :rows="2" style="margin-bottom:.75rem;" />
    <SkeletonCard :rows="2" style="margin-bottom:.75rem;" />
    <SkeletonCard :rows="2" />
  </template>

  <template v-else>
    <div v-if="events.length === 0" class="card" style="padding:2.5rem 1rem; text-align:center;">
      <i class="bi bi-broadcast" style="font-size:2rem; color:var(--color-muted);"></i>
      <div style="margin-top:.5rem; font-weight:600;">No activity yet.</div>
      <div style="font-size:.82rem; color:var(--color-muted); margin-top:.25rem;">
        Log a workout or hit your calorie goal — it'll show up here.
      </div>
    </div>

    <div v-else class="card" style="overflow:hidden;">
      <TransitionGroup name="list" tag="div" style="position:relative;">
        <div v-for="ev in events" :key="ev.id" class="feed-item">
          <div class="feed-avatar">
            <img v-if="ev.avatar_url" :src="ev.avatar_url" :alt="initial(ev.message)" />
            <span v-else>{{ initial(ev.message) }}</span>
          </div>
          <div style="flex:1; min-width:0;">
            <div style="font-size:.92rem; line-height:1.4;">{{ ev.message }}</div>
            <div style="font-size:.74rem; color:var(--color-muted); margin-top:.15rem;">
              {{ relTime(ev.created_at) }}
            </div>
          </div>
        </div>
      </TransitionGroup>
    </div>
  </template>
</template>
