// src/views/FoodView.vue
<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { useRoute } from 'vue-router'
import { supabase } from '../lib/supabase'
import { useAuthStore } from '../stores/auth'
import { MEALS, type MealType } from '../lib/meal'
import SkeletonCard from '../components/SkeletonCard.vue'

type FoodRow = {
  id: number
  item_name: string | null
  calories: number
  protein_g: number
  carbs_g: number
  fat_g: number
  meal_type: MealType
  logged_at: string
}

const auth = useAuthStore()
const route = useRoute()
const entries = ref<FoodRow[]>([])
const loading = ref(true)
const error = ref<string | null>(null)
const deletingId = ref<number | null>(null)

function startOfTodayLocalISO(): string {
  const d = new Date()
  d.setHours(0, 0, 0, 0)
  return d.toISOString()
}

async function load() {
  if (!auth.session) return
  loading.value = true
  const { data, error: e } = await supabase
    .from('food_log')
    .select('id, item_name, calories, protein_g, carbs_g, fat_g, meal_type, logged_at')
    .gte('logged_at', startOfTodayLocalISO())
    .order('logged_at', { ascending: true })
  loading.value = false
  if (e) { error.value = e.message; return }
  entries.value = (data ?? []).map((r) => ({
    ...r,
    calories: Number(r.calories),
    protein_g: Number(r.protein_g),
    carbs_g: Number(r.carbs_g),
    fat_g: Number(r.fat_g),
    meal_type: r.meal_type as MealType
  }))
}

const grouped = computed(() => {
  const map = new Map<MealType, FoodRow[]>()
  for (const m of MEALS) map.set(m.type, [])
  for (const e of entries.value) map.get(e.meal_type)?.push(e)
  return MEALS.map((m) => ({ ...m, rows: map.get(m.type) ?? [] }))
})

function mealTotals(rows: FoodRow[]) {
  return rows.reduce(
    (acc, r) => ({
      calories: acc.calories + r.calories,
      protein_g: acc.protein_g + r.protein_g,
      carbs_g: acc.carbs_g + r.carbs_g,
      fat_g: acc.fat_g + r.fat_g
    }),
    { calories: 0, protein_g: 0, carbs_g: 0, fat_g: 0 }
  )
}

async function remove(row: FoodRow) {
  if (!confirm(`Delete "${row.item_name ?? 'entry'}" (${Math.round(row.calories)} kcal)?`)) return
  deletingId.value = row.id
  const { error: e } = await supabase.from('food_log').delete().eq('id', row.id)
  deletingId.value = null
  if (e) { error.value = e.message; return }
  entries.value = entries.value.filter((x) => x.id !== row.id)
}

onMounted(load)
watch(() => route.name, (name) => { if (name === 'food') load() })
</script>

<template>
  <!-- Quick-add tiles -->
  <div class="action-tiles" style="margin-bottom:.75rem;">
    <RouterLink class="action-tile" :to="{ name: 'log-scan' }">
      <i class="bi bi-upc-scan"></i>
      <span class="action-tile-title">Scan</span>
      <span class="action-tile-sub">Barcode lookup</span>
    </RouterLink>
    <RouterLink class="action-tile" :to="{ name: 'log-quick' }">
      <i class="bi bi-pencil-square"></i>
      <span class="action-tile-title">Quick add</span>
      <span class="action-tile-sub">Manual entry</span>
    </RouterLink>
  </div>

  <div v-if="error" class="alert alert-danger" style="margin-bottom:.75rem;">{{ error }}</div>

  <template v-if="loading">
    <SkeletonCard v-for="i in 4" :key="i" :rows="2" style="margin-bottom:.75rem;" />
  </template>

  <template v-else>
    <div
      v-for="g in grouped"
      :key="g.type"
      class="card"
      style="padding:1rem; margin-bottom:.75rem;"
    >
      <!-- Meal header -->
      <div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:.65rem;">
        <span style="display:flex; align-items:center; gap:.4rem; font-weight:700; font-size:.92rem;">
          <i :class="`bi ${g.icon} text-primary`"></i>
          {{ g.label }}
          <span style="font-size:.75rem; color:var(--color-muted); font-weight:400;">({{ g.rows.length }})</span>
        </span>
        <span class="text-num" style="font-size:.8rem; color:var(--color-muted);">
          {{ Math.round(mealTotals(g.rows).calories) }} kcal
        </span>
      </div>

      <div v-if="g.rows.length === 0"
           style="font-size:.82rem; color:var(--color-muted); font-style:italic;">
        Nothing logged yet.
      </div>

      <TransitionGroup v-else name="list" tag="div" style="position:relative;">
        <div
          v-for="r in g.rows"
          :key="r.id"
          style="display:flex; align-items:center; padding:.55rem 0; border-bottom:1px solid var(--color-border);"
        >
          <div style="flex:1; min-width:0;">
            <div style="font-weight:600; font-size:.9rem; overflow:hidden; text-overflow:ellipsis; white-space:nowrap;">
              {{ r.item_name || 'Untitled' }}
            </div>
            <div class="text-num" style="font-size:.76rem; color:var(--color-muted); margin-top:.05rem;">
              {{ Math.round(r.calories) }} kcal ·
              P {{ Math.round(r.protein_g) }} ·
              C {{ Math.round(r.carbs_g) }} ·
              F {{ Math.round(r.fat_g) }}
            </div>
          </div>
          <button
            type="button"
            class="btn btn-icon btn-danger-ghost btn-sm"
            :disabled="deletingId === r.id"
            :aria-label="`Delete ${r.item_name ?? 'entry'}`"
            @click="remove(r)"
            style="margin-left:.75rem; flex-shrink:0;"
          >
            <span v-if="deletingId === r.id" class="spinner spinner-dark" style="border-top-color:var(--color-danger);"></span>
            <i v-else class="bi bi-trash"></i>
          </button>
        </div>
      </TransitionGroup>
    </div>
  </template>
</template>

// src/views/FoodView.tsx
import { useEffect, useState } from 'react'
import { Link, useLocation } from 'react-router-dom'
import { supabase } from '../lib/supabase'
import { useAuth } from '../hooks/useAuth'
import { MEALS, type MealType } from '../lib/meal'
import SkeletonCard from '../components/SkeletonCard'

type FoodRow = {
  id: number; item_name: string | null;
  calories: number; protein_g: number; carbs_g: number; fat_g: number;
  meal_type: MealType; logged_at: string;
}

const MEAL_COLORS: Record<MealType, string> = {
  breakfast: 'var(--orange)',
  lunch: 'var(--accent)',
  dinner: '#818CF8',
  snack: 'var(--green)',
}

export default function FoodView() {
  const { session } = useAuth()
  const location = useLocation()
  const [entries, setEntries] = useState<FoodRow[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [deletingId, setDeletingId] = useState<number | null>(null)
  const [expanded, setExpanded] = useState<Record<MealType, boolean>>({ breakfast: true, lunch: true, dinner: false, snack: false })

  async function load() {
    if (!session) return
    setLoading(true)
    const since = new Date(); since.setHours(0, 0, 0, 0)
    const { data, error: e } = await supabase
      .from('food_log')
      .select('id, item_name, calories, protein_g, carbs_g, fat_g, meal_type, logged_at')
      .gte('logged_at', since.toISOString())
      .order('logged_at', { ascending: true })
    setLoading(false)
    if (e) { setError(e.message); return }
    setEntries((data ?? []).map(r => ({
      ...r, calories: Number(r.calories), protein_g: Number(r.protein_g),
      carbs_g: Number(r.carbs_g), fat_g: Number(r.fat_g), meal_type: r.meal_type as MealType,
    })))
  }

  useEffect(() => { load() }, [location.pathname])

  async function remove(row: FoodRow) {
    if (!confirm(`Delete "${row.item_name ?? 'entry'}" (${Math.round(row.calories)} kcal)?`)) return
    setDeletingId(row.id)
    const { error: e } = await supabase.from('food_log').delete().eq('id', row.id)
    setDeletingId(null)
    if (e) { setError(e.message); return }
    setEntries(prev => prev.filter(x => x.id !== row.id))
  }

  function groupedEntries(type: MealType) {
    return entries.filter(e => e.meal_type === type)
  }

  function mealTotals(rows: FoodRow[]) {
    return rows.reduce((acc, r) => ({
      calories: acc.calories + r.calories, protein_g: acc.protein_g + r.protein_g,
      carbs_g: acc.carbs_g + r.carbs_g, fat_g: acc.fat_g + r.fat_g,
    }), { calories: 0, protein_g: 0, carbs_g: 0, fat_g: 0 })
  }

  if (loading) return <SkeletonCard rows={4} />

  return (
    <div>
      {error && <div className="alert alert-danger" style={{ marginBottom: '.75rem' }}>{error}</div>}

      {/* Quick add tiles */}
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10, marginBottom: 16 }}>
        <Link to="/food/scan" style={{ display: 'flex', alignItems: 'center', gap: 10, padding: 14, background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 16, textDecoration: 'none' }}>
          <div style={{ width: 38, height: 38, borderRadius: 10, background: 'var(--surface-2)', border: '1px solid var(--border)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
            <i className="bi bi-upc-scan" style={{ fontSize: 18, color: 'var(--text-2)' }} />
          </div>
          <div>
            <div style={{ fontWeight: 700, fontSize: 14, color: 'var(--text)' }}>Scan</div>
            <div style={{ fontSize: 11, color: 'var(--text-2)' }}>Barcode</div>
          </div>
        </Link>
        <Link to="/food/quick" style={{ display: 'flex', alignItems: 'center', gap: 10, padding: 14, background: 'var(--accent-dim)', border: '1px solid var(--accent)', borderRadius: 16, textDecoration: 'none' }}>
          <div style={{ width: 38, height: 38, borderRadius: 10, background: 'var(--accent)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
            <i className="bi bi-pencil-square" style={{ fontSize: 18, color: '#0a0a0a' }} />
          </div>
          <div>
            <div style={{ fontWeight: 700, fontSize: 14, color: 'var(--text)' }}>Quick add</div>
            <div style={{ fontSize: 11, color: 'var(--text-2)' }}>Manual</div>
          </div>
        </Link>
      </div>

      {MEALS.map(meal => {
        const rows = groupedEntries(meal.type)
        const totals = mealTotals(rows)
        const isOpen = expanded[meal.type]
        const iconColor = MEAL_COLORS[meal.type]
        return (
          <div key={meal.type} className="card" style={{ marginBottom: 10, overflow: 'hidden' }}>
            <button
              onClick={() => setExpanded(e => ({ ...e, [meal.type]: !e[meal.type] }))}
              style={{ width: '100%', display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '14px 16px', background: 'none', border: 'none', cursor: 'pointer', textAlign: 'left' }}
            >
              <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
                <div style={{ width: 32, height: 32, borderRadius: 9, flexShrink: 0, background: `${iconColor}18`, border: `1px solid ${iconColor}44`, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                  <i className={`bi ${meal.icon}`} style={{ fontSize: 14, color: iconColor }} />
                </div>
                <span style={{ fontWeight: 700, fontSize: 14, color: 'var(--text)' }}>{meal.label}</span>
                <span className="num" style={{ fontSize: 12, color: 'var(--muted)' }}>{rows.length}</span>
              </div>
              <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
                {totals.calories > 0 && <span className="num" style={{ fontSize: 13, color: 'var(--text-2)', fontWeight: 600 }}>{Math.round(totals.calories)} kcal</span>}
                <i className={`bi bi-chevron-${isOpen ? 'up' : 'down'}`} style={{ fontSize: 11, color: 'var(--muted)' }} />
              </div>
            </button>

            {isOpen && (
              <div style={{ borderTop: '1px solid var(--border)' }}>
                {rows.length === 0 ? (
                  <div style={{ padding: '12px 16px', fontSize: 13, color: 'var(--muted)', fontStyle: 'italic' }}>Nothing logged yet.</div>
                ) : rows.map((item, i) => (
                  <div key={item.id} style={{ display: 'flex', alignItems: 'center', padding: '11px 16px', borderBottom: i < rows.length - 1 ? '1px solid var(--border)' : 'none' }}>
                    <div style={{ flex: 1, minWidth: 0 }}>
                      <div style={{ fontWeight: 600, fontSize: 14, color: 'var(--text)', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{item.item_name || 'Entry'}</div>
                      <div className="num" style={{ fontSize: 11, color: 'var(--text-2)', marginTop: 2 }}>
                        {Math.round(item.calories)} kcal · P{Math.round(item.protein_g)} · C{Math.round(item.carbs_g)} · F{Math.round(item.fat_g)}
                      </div>
                    </div>
                    <button onClick={() => remove(item)} disabled={deletingId === item.id}
                      style={{ width: 28, height: 28, borderRadius: '50%', background: 'none', border: '1px solid var(--border)', cursor: 'pointer', color: 'var(--text-2)', fontSize: 16, display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
                      {deletingId === item.id ? <span className="spinner" style={{ width: 12, height: 12 }} /> : '×'}
                    </button>
                  </div>
                ))}
                <div style={{ padding: '10px 16px' }}>
                  <Link to={`/food/quick?meal=${meal.type}`}
                    style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 6, width: '100%', padding: 10, background: 'var(--surface-2)', border: '1px dashed var(--border)', borderRadius: 10, color: 'var(--text-2)', fontSize: 13, textDecoration: 'none' }}>
                    <i className="bi bi-plus-lg" style={{ fontSize: 13 }} /> Add food
                  </Link>
                </div>
              </div>
            )}
          </div>
        )
      })}
    </div>
  )
}
