// src/views/LogScanView.vue
<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { BrowserMultiFormatReader } from '@zxing/browser'
import { fetchOffProduct, scaleByGrams, type OffProduct } from '../lib/off'
import { supabase } from '../lib/supabase'
import { useAuthStore } from '../stores/auth'
import { MEALS, defaultMealForNow, type MealType } from '../lib/meal'

const auth = useAuthStore()
const router = useRouter()

const videoEl = ref<HTMLVideoElement | null>(null)
const reader = new BrowserMultiFormatReader()
let controls: { stop: () => void } | null = null

const product = ref<OffProduct | null>(null)
const grams = ref<number | null>(100)
const meal = ref<MealType>(defaultMealForNow())
const scanError = ref<string | null>(null)
const lookupError = ref<string | null>(null)
const saving = ref(false)
const manualBarcode = ref('')

async function start() {
  if (!videoEl.value) return
  scanError.value = null
  try {
    controls = await reader.decodeFromVideoDevice(undefined, videoEl.value, async (result) => {
      if (!result || product.value) return
      controls?.stop()
      controls = null
      await lookup(result.getText())
    })
  } catch (e) {
    scanError.value = (e as Error).message
  }
}

async function lookup(barcode: string) {
  lookupError.value = null
  const p = await fetchOffProduct(barcode)
  if (!p) {
    lookupError.value = `No product found for ${barcode}. Try Quick Add.`
    return
  }
  product.value = p
}

async function lookupManual() {
  if (!manualBarcode.value) return
  controls?.stop()
  controls = null
  await lookup(manualBarcode.value.trim())
}

async function save() {
  if (!auth.session || !product.value || !grams.value) return
  saving.value = true
  const macros = scaleByGrams(product.value.per100g, grams.value)
  const { error } = await supabase.from('food_log').insert({
    user_id: auth.session.user.id,
    item_name: product.value.name,
    barcode: product.value.barcode,
    meal_type: meal.value,
    ...macros
  })
  saving.value = false
  if (error) { lookupError.value = error.message; return }
  router.replace({ name: 'food' })
}

onMounted(start)
onBeforeUnmount(() => controls?.stop())
</script>

<template>
  <div v-if="!product">
    <div class="card" style="padding:.75rem; margin-bottom:.75rem; overflow:hidden;">
      <video
        ref="videoEl"
        style="width:100%; max-height:55vh; object-fit:cover; border-radius:.65rem; background:#111;"
        muted
        playsinline
      />
    </div>
    <div v-if="scanError" class="alert alert-warning" style="margin-bottom:.75rem;">{{ scanError }}</div>

    <div class="card" style="padding:1.1rem;">
      <label class="form-label" style="text-transform:uppercase; letter-spacing:.06em; font-size:.72rem;">
        Or enter barcode manually
      </label>
      <div style="display:flex; gap:.5rem;">
        <input
          v-model="manualBarcode"
          inputmode="numeric"
          class="form-input text-num"
          placeholder="EAN / UPC"
          style="flex:1;"
        />
        <button class="btn btn-ghost" type="button" @click="lookupManual">
          <i class="bi bi-search"></i> Look up
        </button>
      </div>
    </div>

    <div v-if="lookupError" class="alert alert-warning" style="margin-top:.75rem;">{{ lookupError }}</div>
  </div>

  <form v-else @submit.prevent="save">
    <!-- Product info -->
    <div class="card" style="padding:1.1rem; margin-bottom:.75rem;">
      <div style="font-weight:700; font-size:1rem; margin-bottom:.2rem;">{{ product.name }}</div>
      <div style="font-size:.78rem; color:var(--color-muted); margin-bottom:.85rem;">Barcode {{ product.barcode }}</div>
      <div style="display:grid; grid-template-columns:repeat(4,1fr); gap:.5rem; text-align:center;">
        <div v-for="(label, key) in { calories:'kcal/100g', protein_g:'Protein', carbs_g:'Carbs', fat_g:'Fat' }"
             :key="key">
          <div class="text-num" style="font-weight:700; font-size:.95rem;">
            {{ (product.per100g as any)[key] }}
          </div>
          <div style="font-size:.7rem; color:var(--color-muted);">{{ label }}</div>
        </div>
      </div>
    </div>

    <!-- Meal + grams -->
    <div class="card" style="padding:1.1rem; margin-bottom:.75rem;">
      <div class="form-label">Meal</div>
      <div style="display:grid; grid-template-columns:repeat(4,1fr); gap:.4rem; margin-bottom:1rem;">
        <label
          v-for="m in MEALS"
          :key="m.type"
          :style="`
            display:flex; flex-direction:column; align-items:center; gap:.2rem;
            padding:.5rem .25rem; border-radius:.65rem; cursor:pointer;
            border:2px solid ${meal === m.type ? 'var(--color-primary)' : 'var(--color-border)'};
            background:${meal === m.type ? 'rgba(79,70,229,.06)' : '#fff'};
            transition:all .15s;
          `"
        >
          <input type="radio" :value="m.type" v-model="meal" style="display:none;" />
          <i :class="`bi ${m.icon}`"
             :style="`font-size:1.2rem; color:${meal === m.type ? 'var(--color-primary)' : 'var(--color-muted)'};`"></i>
          <span style="font-size:.7rem; font-weight:600;">{{ m.label }}</span>
        </label>
      </div>
      <label class="form-label">Amount (grams)</label>
      <input v-model.number="grams" type="number" min="1" required class="form-input text-num" />
    </div>

    <button type="submit" class="btn btn-primary w-full" :disabled="saving || !grams" style="margin-bottom:.5rem;">
      <span v-if="saving" class="spinner"></span>
      {{ saving ? 'Saving…' : 'Log food' }}
    </button>
    <button type="button" class="btn btn-link w-full" @click="product = null">
      ← Scan another
    </button>
    <div v-if="lookupError" class="alert alert-danger" style="margin-top:.75rem;">{{ lookupError }}</div>
  </form>
</template>

// src/views/LogScanView.tsx
import { useEffect, useRef, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { BrowserMultiFormatReader } from '@zxing/browser'
import { fetchOffProduct, scaleByGrams, type OffProduct } from '../lib/off'
import { supabase } from '../lib/supabase'
import { useAuth } from '../hooks/useAuth'
import { MEALS, defaultMealForNow, type MealType } from '../lib/meal'

const MEAL_COLORS: Record<MealType, string> = {
  breakfast: 'var(--orange)', lunch: 'var(--accent)',
  dinner: '#818CF8', snack: 'var(--green)',
}

export default function LogScanView() {
  const { session } = useAuth()
  const navigate = useNavigate()
  const videoRef = useRef<HTMLVideoElement>(null)
  const reader = useRef(new BrowserMultiFormatReader())
  const controlsRef = useRef<{ stop: () => void } | null>(null)

  const [product, setProduct] = useState<OffProduct | null>(null)
  const [grams, setGrams] = useState<number>(100)
  const [meal, setMeal] = useState<MealType>(defaultMealForNow())
  const [scanError, setScanError] = useState<string | null>(null)
  const [lookupError, setLookupError] = useState<string | null>(null)
  const [saving, setSaving] = useState(false)
  const [manualBarcode, setManualBarcode] = useState('')

  async function startScan() {
    if (!videoRef.current) return
    setScanError(null)
    try {
      controlsRef.current = await reader.current.decodeFromVideoDevice(
        undefined, videoRef.current,
        async (result) => {
          if (!result || product) return
          controlsRef.current?.stop()
          controlsRef.current = null
          await lookup(result.getText())
        }
      )
    } catch (e) {
      setScanError((e as Error).message)
    }
  }

  async function lookup(barcode: string) {
    setLookupError(null)
    const p = await fetchOffProduct(barcode)
    if (!p) {
      setLookupError(`No product found for ${barcode}. Try Quick Add.`)
      return
    }
    setProduct(p)
  }

  useEffect(() => {
    startScan()
    return () => { controlsRef.current?.stop() }
  }, [])

  async function save() {
    if (!session || !product) return
    setSaving(true)
    const macros = scaleByGrams(product.per100g, grams)
    const { error: e } = await supabase.from('food_log').insert({
      user_id: session.user.id,
      item_name: product.name,
      ...macros,
      meal_type: meal,
    })
    setSaving(false)
    if (e) { setLookupError(e.message); return }
    navigate('/food', { replace: true })
  }

  return (
    <div>
      {!product ? (
        <div className="card fade-up" style={{ overflow: 'hidden' }}>
          <video ref={videoRef} style={{ width: '100%', display: 'block', aspectRatio: '16/9', background: '#000' }} />
          <div style={{ padding: '1rem' }}>
            {scanError && <div className="alert alert-danger" style={{ marginBottom: '.75rem' }}>{scanError}</div>}
            <div style={{ display: 'flex', gap: '.5rem' }}>
              <input className="form-input" placeholder="Or enter barcode manually…"
                value={manualBarcode} onChange={e => setManualBarcode(e.target.value)}
                onKeyDown={e => e.key === 'Enter' && lookup(manualBarcode.trim())} />
              <button className="btn btn-accent btn-sm" style={{ flexShrink: 0 }}
                onClick={() => lookup(manualBarcode.trim())} disabled={!manualBarcode}>
                Go
              </button>
            </div>
            {lookupError && <div className="alert alert-danger" style={{ marginTop: '.75rem' }}>{lookupError}</div>}
          </div>
        </div>
      ) : (
        <div className="card fade-up" style={{ padding: '1.25rem' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '1rem' }}>
            <div>
              <div style={{ fontWeight: 700, fontSize: 16, color: 'var(--text)' }}>{product.name}</div>
              <div className="num" style={{ fontSize: 12, color: 'var(--text-2)', marginTop: 4 }}>
                per {grams}g: {Math.round(product.per100g.calories * grams / 100)} kcal
              </div>
            </div>
            <button onClick={() => setProduct(null)} style={{ background: 'none', border: '1px solid var(--border)', borderRadius: 8, padding: '4px 10px', color: 'var(--text-2)', cursor: 'pointer', fontSize: 12 }}>
              Scan again
            </button>
          </div>

          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 6, marginBottom: '1rem', background: 'var(--surface-2)', borderRadius: 12, padding: 12 }}>
            {[
              { label: 'Calories', val: Math.round(product.per100g.calories * grams / 100) },
              { label: 'Protein', val: `${Math.round(product.per100g.protein_g * grams / 100)}g` },
              { label: 'Carbs', val: `${Math.round(product.per100g.carbs_g * grams / 100)}g` },
              { label: 'Fat', val: `${Math.round(product.per100g.fat_g * grams / 100)}g` },
            ].map(m => (
              <div key={m.label} style={{ textAlign: 'center' }}>
                <div className="num" style={{ fontSize: 16, fontWeight: 700, color: 'var(--text)' }}>{m.val}</div>
                <div style={{ fontSize: 10, color: 'var(--text-2)', marginTop: 2 }}>{m.label}</div>
              </div>
            ))}
          </div>

          <div style={{ marginBottom: '1rem' }}>
            <label className="form-label">Serving size (g)</label>
            <input type="number" inputMode="numeric" min="1" className="form-input num"
              value={grams} onChange={e => setGrams(Number(e.target.value))} />
          </div>

          <div className="form-label" style={{ marginBottom: '.5rem' }}>Meal</div>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4,1fr)', gap: '.4rem', marginBottom: '1rem' }}>
            {MEALS.map(m => {
              const active = meal === m.type
              const color = MEAL_COLORS[m.type]
              return (
                <button key={m.type} type="button" onClick={() => setMeal(m.type)}
                  style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '.2rem', padding: '.5rem .25rem', borderRadius: '.65rem', cursor: 'pointer', border: `2px solid ${active ? color : 'var(--border)'}`, background: active ? `${color}15` : 'var(--surface-2)' }}>
                  <i className={`bi ${m.icon}`} style={{ fontSize: '1.2rem', color: active ? color : 'var(--muted)' }} />
                  <span style={{ fontSize: '.7rem', fontWeight: 600, color: active ? color : 'var(--text-2)' }}>{m.label}</span>
                </button>
              )
            })}
          </div>

          <button className="btn btn-accent" style={{ width: '100%', padding: '.75rem' }} onClick={save} disabled={saving}>
            {saving && <span className="spinner" />}
            {saving ? 'Logging…' : 'Add to log'}
          </button>
        </div>
      )}
    </div>
  )
}
