// src/views/ProfileView.vue
<script setup lang="ts">
import { onMounted, reactive, ref, watch } from 'vue'
import { useRouter } from 'vue-router'
import { supabase } from '../lib/supabase'
import { useAuthStore } from '../stores/auth'
import { fetchWeightHistory, type WeightEntry } from '../lib/queries/weightHistory'
import WeightProgressChart from '../components/charts/WeightProgressChart.vue'

const auth   = useAuthStore()
const router = useRouter()

// ── Profile form ───────────────────────────────────────────────────────
const form = reactive({
  name:             '',
  age:              null as number | null,
  weight_kg:        null as number | null,
  height_cm:        null as number | null,
  target_calories:  0,
  target_protein_g: 0,
  target_carbs_g:   0,
  target_fat_g:     0
})
const saving  = ref(false)
const message = ref<string | null>(null)
const error   = ref<string | null>(null)

watch(
  () => auth.profile,
  (p) => {
    if (!p) return
    form.name             = p.name
    form.age              = p.age
    form.weight_kg        = p.weight_kg
    form.height_cm        = p.height_cm
    form.target_calories  = p.target_calories
    form.target_protein_g = p.target_protein_g
    form.target_carbs_g   = p.target_carbs_g
    form.target_fat_g     = p.target_fat_g
  },
  { immediate: true }
)

async function save() {
  if (!auth.session) return
  saving.value  = true
  error.value   = null
  message.value = null
  const { error: e } = await supabase
    .from('profile')
    .update({ ...form })
    .eq('id', auth.session.user.id)
  saving.value = false
  if (e) { error.value = e.message; return }
  await auth.loadProfile()
  message.value = 'Saved'
}

// ── Avatar upload ──────────────────────────────────────────────────────
const fileInput      = ref<HTMLInputElement | null>(null)
const avatarPreview  = ref<string | null>(null)
const uploading      = ref(false)
const uploadError    = ref<string | null>(null)

watch(
  () => auth.profile?.avatar_url,
  (url) => { if (url && !avatarPreview.value) avatarPreview.value = url },
  { immediate: true }
)

function pickFile() { fileInput.value?.click() }

async function onFileChange(evt: Event) {
  const file = (evt.target as HTMLInputElement).files?.[0]
  if (!file || !auth.session) return
  if (!file.type.startsWith('image/')) { uploadError.value = 'Please choose an image file.'; return }
  if (file.size > 5 * 1024 * 1024) { uploadError.value = 'Image must be under 5 MB.'; return }
  if (avatarPreview.value?.startsWith('blob:')) URL.revokeObjectURL(avatarPreview.value)
  avatarPreview.value = URL.createObjectURL(file)
  uploading.value = true
  uploadError.value = null
  const ext  = file.name.split('.').pop() ?? 'jpg'
  const path = `${auth.session.user.id}/avatar.${ext}`
  const { error: upErr } = await supabase.storage
    .from('avatars')
    .upload(path, file, { upsert: true, contentType: file.type })
  if (upErr) { uploading.value = false; uploadError.value = upErr.message; return }
  const { data: { publicUrl } } = supabase.storage.from('avatars').getPublicUrl(path)
  const urlWithBust = `${publicUrl}?t=${Date.now()}`
  const { error: profileErr } = await supabase
    .from('profile')
    .update({ avatar_url: urlWithBust })
    .eq('id', auth.session.user.id)
  uploading.value = false
  if (profileErr) { uploadError.value = profileErr.message; return }
  avatarPreview.value = urlWithBust
  await auth.loadProfile()
}

// ── Weight log ─────────────────────────────────────────────────────────
const weightKg    = ref<number | null>(null)
const weightDate  = ref(new Date().toISOString().slice(0, 10))
const savingWeight = ref(false)
const weightError  = ref<string | null>(null)
const weightHistory = ref<WeightEntry[]>([])

async function loadWeightHistory() {
  if (!auth.session) return
  weightHistory.value = await fetchWeightHistory(auth.session.user.id)
}

async function logWeight() {
  if (!auth.session || !weightKg.value) return
  savingWeight.value = true
  weightError.value  = null
  const { error: e } = await supabase
    .from('weight_log')
    .upsert({
      user_id:   auth.session.user.id,
      weight_kg: weightKg.value,
      logged_at: weightDate.value
    }, { onConflict: 'user_id,logged_at' })
  savingWeight.value = false
  if (e) { weightError.value = e.message; return }
  await loadWeightHistory()
  weightKg.value = null
}

// ── Sign out ───────────────────────────────────────────────────────────
async function signOut() {
  await auth.signOut()
  router.replace({ name: 'login' })
}

onMounted(loadWeightHistory)
</script>

<template>
  <!-- Avatar card -->
  <div class="card" style="padding:1.1rem; margin-bottom:.75rem;">
    <div style="display:flex; align-items:center; gap:1rem;">
      <button
        type="button"
        class="avatar-upload-btn"
        :disabled="uploading"
        title="Change profile picture"
        @click="pickFile"
      >
        <img v-if="avatarPreview" :src="avatarPreview" alt="Profile picture" class="avatar-img" />
        <span v-else class="avatar-placeholder">
          {{ (auth.profile?.name ?? '?')[0].toUpperCase() }}
        </span>
        <span class="avatar-overlay"><i class="bi bi-camera-fill"></i></span>
        <span v-if="uploading" class="avatar-spinner">
          <span class="spinner" style="border-color:rgba(255,255,255,.3); border-top-color:#fff;"></span>
        </span>
      </button>

      <div style="flex:1; min-width:0;">
        <div style="font-weight:700; font-size:.95rem;">{{ auth.profile?.name }}</div>
        <div style="font-size:.8rem; color:var(--color-muted); margin-bottom:.5rem; overflow:hidden; text-overflow:ellipsis; white-space:nowrap;">
          {{ auth.session?.user.email }}
        </div>
        <button
          type="button"
          class="btn btn-ghost btn-sm"
          :disabled="uploading"
          @click="pickFile"
        >
          <i class="bi bi-camera"></i>
          {{ avatarPreview ? 'Change photo' : 'Add photo' }}
        </button>
      </div>
    </div>
    <div v-if="uploadError" class="alert alert-danger" style="margin-top:.75rem; margin-bottom:0;">
      {{ uploadError }}
    </div>
  </div>

  <!-- Hidden file input -->
  <input
    ref="fileInput"
    type="file"
    accept="image/jpeg,image/png,image/webp,image/gif"
    style="display:none;"
    @change="onFileChange"
  />

  <!-- Profile form -->
  <div class="card" style="padding:1.1rem; margin-bottom:.75rem;">
    <form @submit.prevent="save">
      <div style="margin-bottom:.85rem;">
        <label class="form-label">Display name</label>
        <input v-model="form.name" required class="form-input" />
      </div>

      <div style="display:grid; grid-template-columns:repeat(3,1fr); gap:.6rem; margin-bottom:.85rem;">
        <div>
          <label class="form-label">Age</label>
          <input v-model.number="form.age" type="number" min="0" class="form-input" />
        </div>
        <div>
          <label class="form-label">Weight (kg)</label>
          <input v-model.number="form.weight_kg" type="number" step="0.1" min="0" class="form-input" />
        </div>
        <div>
          <label class="form-label">Height (cm)</label>
          <input v-model.number="form.height_cm" type="number" min="0" class="form-input" />
        </div>
      </div>

      <div style="font-weight:700; font-size:.88rem; margin-bottom:.75rem; color:#374151;">Daily targets</div>
      <div style="display:grid; grid-template-columns:1fr 1fr; gap:.6rem; margin-bottom:1.1rem;">
        <div>
          <label class="form-label">Calories</label>
          <input v-model.number="form.target_calories" type="number" min="0" required class="form-input" />
        </div>
        <div>
          <label class="form-label">Protein (g)</label>
          <input v-model.number="form.target_protein_g" type="number" min="0" required class="form-input" />
        </div>
        <div>
          <label class="form-label">Carbs (g)</label>
          <input v-model.number="form.target_carbs_g" type="number" min="0" required class="form-input" />
        </div>
        <div>
          <label class="form-label">Fat (g)</label>
          <input v-model.number="form.target_fat_g" type="number" min="0" required class="form-input" />
        </div>
      </div>

      <button type="submit" class="btn btn-primary w-full" :disabled="saving">
        <span v-if="saving" class="spinner"></span>
        {{ saving ? 'Saving…' : 'Save' }}
      </button>
      <div v-if="message" class="alert alert-success" style="margin-top:.75rem; margin-bottom:0;">{{ message }}</div>
      <div v-if="error"   class="alert alert-danger"  style="margin-top:.75rem; margin-bottom:0;">{{ error }}</div>
    </form>
  </div>

  <!-- Weight log -->
  <div class="card" style="padding:1.1rem; margin-bottom:.75rem;">
    <div style="font-weight:700; font-size:.9rem; margin-bottom:.85rem; display:flex; align-items:center; gap:.4rem;">
      <i class="bi bi-graph-up-arrow text-primary"></i>
      Weight progress
    </div>

    <form @submit.prevent="logWeight" style="display:grid; grid-template-columns:1fr 1fr auto; gap:.5rem; margin-bottom:.85rem;">
      <input
        v-model="weightDate"
        type="date"
        class="form-input form-input-sm"
        :max="new Date().toISOString().slice(0,10)"
      />
      <input
        v-model.number="weightKg"
        type="number"
        step="0.1"
        min="0"
        class="form-input form-input-sm text-num"
        placeholder="kg"
        required
      />
      <button type="submit" class="btn btn-primary btn-sm" :disabled="savingWeight || !weightKg">
        <span v-if="savingWeight" class="spinner"></span>
        <i v-else class="bi bi-plus-lg"></i>
        Log
      </button>
    </form>

    <div v-if="weightError" class="alert alert-danger" style="margin-bottom:.75rem;">{{ weightError }}</div>

    <div v-if="weightHistory.length === 0" style="font-size:.82rem; color:var(--color-muted); font-style:italic;">
      No weight entries yet. Log your first one above.
    </div>
    <WeightProgressChart v-else :data="weightHistory" />
  </div>

  <button class="btn btn-danger-ghost w-full" @click="signOut">
    <i class="bi bi-box-arrow-right"></i> Sign out
  </button>
</template>

// src/views/ProfileView.tsx
import { useEffect, useRef, useState } from 'react'
import { supabase } from '../lib/supabase'
import { useAuth } from '../hooks/useAuth'
import { fetchWeightHistory, type WeightEntry } from '../lib/queries/weightHistory'
import { useTheme } from '../hooks/useTheme'
import WeightChart from '../components/WeightChart'
import SkeletonCard from '../components/SkeletonCard'

export default function ProfileView() {
  const { session, profile, loadProfile, signOut } = useAuth()
  const { dark, toggle } = useTheme()

  const [form, setForm] = useState({
    name: '', age: null as number | null,
    weight_kg: null as number | null, height_cm: null as number | null,
    target_calories: 0, target_protein_g: 0, target_carbs_g: 0, target_fat_g: 0,
  })
  const [saving, setSaving] = useState(false)
  const [message, setMessage] = useState<string | null>(null)
  const [error, setError] = useState<string | null>(null)

  const [weightHistory, setWeightHistory] = useState<WeightEntry[]>([])
  const [newWeight, setNewWeight] = useState('')
  const [loggingWeight, setLoggingWeight] = useState(false)

  const fileInputRef = useRef<HTMLInputElement>(null)
  const [avatarPreview, setAvatarPreview] = useState<string | null>(null)
  const [uploading, setUploading] = useState(false)
  const [uploadError, setUploadError] = useState<string | null>(null)

  useEffect(() => {
    if (!profile) return
    setForm({
      name: profile.name, age: profile.age, weight_kg: profile.weight_kg,
      height_cm: profile.height_cm, target_calories: profile.target_calories,
      target_protein_g: profile.target_protein_g, target_carbs_g: profile.target_carbs_g,
      target_fat_g: profile.target_fat_g,
    })
    if (profile.avatar_url && !avatarPreview) setAvatarPreview(profile.avatar_url)
  }, [profile])

  useEffect(() => {
    if (!session) return
    fetchWeightHistory(session.user.id).then(setWeightHistory)
  }, [session])

  function set<K extends keyof typeof form>(k: K, v: typeof form[K]) {
    setForm(f => ({ ...f, [k]: v }))
  }

  async function save(e: React.FormEvent) {
    e.preventDefault()
    if (!session) return
    setSaving(true)
    setError(null)
    setMessage(null)
    const { error: e2 } = await supabase.from('profile').update({ ...form }).eq('id', session.user.id)
    setSaving(false)
    if (e2) { setError(e2.message); return }
    await loadProfile()
    setMessage('Saved')
    setTimeout(() => setMessage(null), 2500)
  }

  async function logWeight(e: React.FormEvent) {
    e.preventDefault()
    if (!session || !newWeight) return
    const w = Number(newWeight)
    if (isNaN(w) || w <= 0) return
    setLoggingWeight(true)
    const { error: e2 } = await supabase.from('weight_log').insert({ user_id: session.user.id, weight_kg: w })
    setLoggingWeight(false)
    if (e2) return
    setNewWeight('')
    const updated = await fetchWeightHistory(session.user.id)
    setWeightHistory(updated)
    set('weight_kg', w)
    await supabase.from('profile').update({ weight_kg: w }).eq('id', session.user.id)
    await loadProfile()
  }

  async function onFileChange(evt: React.ChangeEvent<HTMLInputElement>) {
    const file = evt.target.files?.[0]
    if (!file || !session) return
    if (!file.type.startsWith('image/')) { setUploadError('Please choose an image file.'); return }
    if (file.size > 5 * 1024 * 1024) { setUploadError('Image must be under 5 MB.'); return }
    if (avatarPreview?.startsWith('blob:')) URL.revokeObjectURL(avatarPreview)
    setAvatarPreview(URL.createObjectURL(file))
    setUploading(true)
    setUploadError(null)
    const ext = file.name.split('.').pop() ?? 'jpg'
    const path = `${session.user.id}/avatar.${ext}`
    const { error: upErr } = await supabase.storage.from('avatars').upload(path, file, { upsert: true, contentType: file.type })
    if (upErr) { setUploading(false); setUploadError(upErr.message); return }
    const { data: { publicUrl } } = supabase.storage.from('avatars').getPublicUrl(path)
    const urlWithBust = `${publicUrl}?t=${Date.now()}`
    await supabase.from('profile').update({ avatar_url: urlWithBust }).eq('id', session.user.id)
    setUploading(false)
    setAvatarPreview(urlWithBust)
    await loadProfile()
  }

  if (!profile) return <SkeletonCard rows={5} />

  const initials = profile.name ? profile.name.split(' ').map(n => n[0]).slice(0, 2).join('').toUpperCase() : '?'

  return (
    <div>
      {/* Avatar + name */}
      <div className="card fade-up" style={{ padding: '1.25rem', marginBottom: '.75rem' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '1rem', marginBottom: '1.1rem' }}>
          <button onClick={() => fileInputRef.current?.click()} style={{ position: 'relative', width: 72, height: 72, borderRadius: '50%', border: 'none', padding: 0, background: 'none', cursor: 'pointer', flexShrink: 0 }}>
            {avatarPreview
              ? <img src={avatarPreview} alt="" style={{ width: 72, height: 72, borderRadius: '50%', objectFit: 'cover', border: '2px solid var(--border)' }} />
              : <div style={{ width: 72, height: 72, borderRadius: '50%', background: 'var(--accent)', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#0a0a0a', fontSize: '1.5rem', fontWeight: 800 }}>{initials}</div>
            }
            {uploading && (
              <div style={{ position: 'absolute', inset: 0, borderRadius: '50%', background: 'rgba(0,0,0,.5)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                <span className="spinner" style={{ borderTopColor: 'var(--accent)', borderColor: 'rgba(255,255,255,.2)' }} />
              </div>
            )}
          </button>
          <input ref={fileInputRef} type="file" accept="image/*" style={{ display: 'none' }} onChange={onFileChange} />
          <div>
            <div style={{ fontWeight: 800, fontSize: '1.2rem', color: 'var(--text)', letterSpacing: '-.02em' }}>{profile.name}</div>
            <div style={{ fontSize: '.82rem', color: 'var(--text-2)', marginTop: 2 }}>{session?.user.email}</div>
          </div>
        </div>
        {uploadError && <div className="alert alert-danger" style={{ marginBottom: '.75rem' }}>{uploadError}</div>}
      </div>

      {/* Appearance */}
      <div className="card fade-up" style={{ padding: '1.1rem', marginBottom: '.75rem', animationDelay: '.04s' }}>
        <div className="section-label">Appearance</div>
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
            <span style={{ fontSize: 20 }}>{dark ? '🌙' : '☀️'}</span>
            <div>
              <div style={{ fontWeight: 600, fontSize: 14, color: 'var(--text)' }}>{dark ? 'Dark mode' : 'Light mode'}</div>
              <div style={{ fontSize: 12, color: 'var(--text-2)' }}>Toggle theme</div>
            </div>
          </div>
          <button className={`toggle-track ${dark ? 'on' : ''}`} onClick={toggle} aria-label="Toggle theme">
            <div className="toggle-thumb" />
          </button>
        </div>
      </div>

      {/* Weight */}
      <div className="card fade-up" style={{ padding: '1.1rem', marginBottom: '.75rem', animationDelay: '.08s' }}>
        <div className="section-label">Weight log</div>
        <WeightChart data={weightHistory} />
        <form onSubmit={logWeight} style={{ display: 'flex', gap: '.5rem', marginTop: '1rem' }}>
          <input type="number" inputMode="decimal" step="0.1" min="0" className="form-input num"
            placeholder="kg" style={{ flex: 1 }} value={newWeight} onChange={e => setNewWeight(e.target.value)} />
          <button type="submit" className="btn btn-accent btn-sm" style={{ flexShrink: 0 }} disabled={loggingWeight || !newWeight}>
            {loggingWeight ? <span className="spinner" /> : 'Log'}
          </button>
        </form>
      </div>

      {/* Profile form */}
      <div className="card fade-up" style={{ padding: '1.25rem', marginBottom: '.75rem', animationDelay: '.12s' }}>
        <div className="section-label">Profile</div>
        <form onSubmit={save}>
          <div style={{ marginBottom: '.85rem' }}>
            <label className="form-label">Display name</label>
            <input required className="form-input" value={form.name} onChange={e => set('name', e.target.value)} />
          </div>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3,1fr)', gap: '.6rem', marginBottom: '.85rem' }}>
            {([['age', 'Age'], ['weight_kg', 'Weight (kg)'], ['height_cm', 'Height (cm)']] as const).map(([k, label]) => (
              <div key={k}>
                <label className="form-label">{label}</label>
                <input type="number" inputMode="numeric" className="form-input num"
                  value={form[k] ?? ''} onChange={e => set(k, e.target.value ? Number(e.target.value) : null)} />
              </div>
            ))}
          </div>

          <div className="section-label" style={{ marginTop: '1rem' }}>Daily targets</div>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '.65rem', marginBottom: '1.1rem' }}>
            {([['target_calories', 'Calories'], ['target_protein_g', 'Protein (g)'], ['target_carbs_g', 'Carbs (g)'], ['target_fat_g', 'Fat (g)']] as const).map(([k, label]) => (
              <div key={k}>
                <label className="form-label">{label}</label>
                <input type="number" inputMode="numeric" min="0" className="form-input num"
                  value={form[k]} onChange={e => set(k, Number(e.target.value))} />
              </div>
            ))}
          </div>

          <button type="submit" className="btn btn-accent" style={{ width: '100%', padding: '.75rem' }} disabled={saving}>
            {saving && <span className="spinner" />}
            {saving ? 'Saving…' : 'Save changes'}
          </button>
          {message && <div className="alert alert-success" style={{ marginTop: '.75rem' }}>{message}</div>}
          {error && <div className="alert alert-danger" style={{ marginTop: '.75rem' }}>{error}</div>}
        </form>
      </div>

      {/* Sign out */}
      <div className="card fade-up" style={{ padding: '1rem', marginBottom: '1rem', animationDelay: '.16s' }}>
        <button onClick={signOut} className="btn btn-danger" style={{ width: '100%', padding: '.75rem' }}>
          <i className="bi bi-box-arrow-right" /> Sign out
        </button>
      </div>
    </div>
  )
}
