// src/views/TodayView.tsx
import { useEffect, useState } from 'react'
import { Link, useLocation } from 'react-router-dom'
import { supabase } from '../lib/supabase'
import { useAuth } from '../hooks/useAuth'
import { fetchTodayTotals, type DayTotals } from '../lib/queries/today'
import { fetchWeeklyCalories, type DayCalories } from '../lib/queries/weeklyNutrition'
import CalorieRing from '../components/CalorieRing'
import MacroBar from '../components/MacroBar'
import WeekChart from '../components/WeekChart'
import SkeletonCard from '../components/SkeletonCard'

type SessionSummary = { id: number; name: string | null; started_at: string; setCount: number }

function fmtTime(iso: string) {
  return new Date(iso).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
}

export default function TodayView() {
  const { session, profile } = useAuth()
  const location = useLocation()
  const [totals, setTotals] = useState<DayTotals>({ calories: 0, protein_g: 0, carbs_g: 0, fat_g: 0 })
  const [weeklyData, setWeeklyData] = useState<DayCalories[]>([])
  const [todaySessions, setTodaySessions] = useState<SessionSummary[]>([])
  const [loading, setLoading] = useState(true)

  async function load() {
    if (!session) return
    setLoading(true)
    const [t, weekly] = await Promise.all([
      fetchTodayTotals(session.user.id),
      fetchWeeklyCalories(session.user.id),
    ])
    setTotals(t)
    setWeeklyData(weekly)

    const since = new Date()
    since.setHours(0, 0, 0, 0)
    const { data: sessions } = await supabase
      .from('workout_session')
      .select('id, name, started_at')
      .gte('started_at', since.toISOString())
      .order('started_at', { ascending: false })

    const ids = (sessions ?? []).map(s => s.id)
    const counts = new Map<number, number>()
    if (ids.length > 0) {
      const { data: logs } = await supabase.from('workout_log').select('session_id').in('session_id', ids)
      for (const l of logs ?? []) counts.set(l.session_id, (counts.get(l.session_id) ?? 0) + 1)
    }
    setTodaySessions((sessions ?? []).map(s => ({ id: s.id, name: s.name, started_at: s.started_at, setCount: counts.get(s.id) ?? 0 })))
    setLoading(false)
  }

  useEffect(() => { load() }, [location.pathname])

  if (loading) return (
    <div>
      <SkeletonCard rows={4} />
      <SkeletonCard rows={3} />
    </div>
  )

  if (!profile) return null

  const weekCals = weeklyData.map(d => d.calories)
  const weekLabels = weeklyData.map(d => new Date(d.date + 'T12:00:00').toLocaleDateString(undefined, { weekday: 'narrow' }))

  return (
    <div>
      {/* Hero nutrition card */}
      <div className="card fade-up" style={{ padding: '20px 16px', marginBottom: 12 }}>
        <CalorieRing cal={totals.calories} targetCal={profile.target_calories} />
        <MacroBar label="Protein" current={totals.protein_g} target={profile.target_protein_g} color="var(--accent)" />
        <MacroBar label="Carbs"   current={totals.carbs_g}   target={profile.target_carbs_g}   color="var(--orange)" />
        <MacroBar label="Fat"     current={totals.fat_g}     target={profile.target_fat_g}     color="var(--green)" />
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10, marginTop: 18 }}>
          <Link to="/food/scan" style={{ display: 'flex', flexDirection: 'column', gap: 5, padding: 14, background: 'var(--surface-2)', border: '1px solid var(--border)', borderRadius: 16, textDecoration: 'none' }}>
            <i className="bi bi-upc-scan" style={{ fontSize: 22, color: 'var(--text-2)' }} />
            <span style={{ fontWeight: 700, fontSize: 14, color: 'var(--text)' }}>Scan</span>
            <span style={{ fontSize: 11, color: 'var(--text-2)' }}>Barcode lookup</span>
          </Link>
          <Link to="/food/quick" style={{ display: 'flex', flexDirection: 'column', gap: 5, padding: 14, background: 'var(--accent-dim)', border: '1px solid var(--accent)', borderRadius: 16, textDecoration: 'none' }}>
            <i className="bi bi-pencil-square" style={{ fontSize: 22, color: 'var(--accent)' }} />
            <span style={{ fontWeight: 700, fontSize: 14, color: 'var(--text)' }}>Quick add</span>
            <span style={{ fontSize: 11, color: 'var(--text-2)' }}>Manual entry</span>
          </Link>
        </div>
      </div>

      {/* Weekly calories */}
      <div className="card fade-up" style={{ padding: 16, marginBottom: 12, animationDelay: '.05s' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 }}>
          <span className="section-label" style={{ margin: 0 }}>7-day calories</span>
          <div style={{ display: 'flex', alignItems: 'center', gap: 5, fontSize: 11, color: 'var(--text-2)' }}>
            <div style={{ width: 14, height: 2, background: 'var(--orange)', opacity: 0.6, borderRadius: 1 }} />
            <span>goal</span>
          </div>
        </div>
        {weekCals.length > 0 && <WeekChart data={weekCals} target={profile.target_calories} labels={weekLabels} />}
      </div>

      {/* Today's training */}
      <div className="card fade-up" style={{ padding: 16, animationDelay: '.1s' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 14 }}>
          <span style={{ fontSize: 14, fontWeight: 700, color: 'var(--text)', display: 'flex', alignItems: 'center', gap: 6 }}>
            <i className="bi bi-lightning-charge-fill" style={{ color: 'var(--accent)', fontSize: 14 }} />
            Today's Training
          </span>
          <Link to="/workout" style={{ fontSize: 12, color: 'var(--accent)', textDecoration: 'none', fontWeight: 700 }}>View all →</Link>
        </div>
        {todaySessions.length === 0 ? (
          <p style={{ fontSize: 13, color: 'var(--text-2)', fontStyle: 'italic', margin: 0 }}>
            No workouts yet.{' '}
            <Link to="/workout" style={{ color: 'var(--accent)', textDecoration: 'none', fontWeight: 700 }}>Start one →</Link>
          </p>
        ) : todaySessions.map(s => (
          <Link key={s.id} to={`/workout/${s.id}`} style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '12px 0', borderTop: '1px solid var(--border)', textDecoration: 'none', color: 'inherit' }}>
            <div>
              <div style={{ fontWeight: 700, fontSize: 14, color: 'var(--text)' }}>{s.name || 'Untitled workout'}</div>
              <div className="num" style={{ fontSize: 12, color: 'var(--text-2)', marginTop: 3 }}>
                {s.setCount} sets · {fmtTime(s.started_at)}
              </div>
            </div>
            <div style={{ width: 34, height: 34, borderRadius: '50%', background: 'var(--accent-dim)', border: '1px solid var(--accent)', display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'var(--accent)', fontSize: 18, fontWeight: 700 }}>›</div>
          </Link>
        ))}
      </div>
    </div>
  )
}

// src/views/TodayView.vue
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useAuthStore } from '../stores/auth'
import { fetchTodayTotals, type DayTotals } from '../lib/queries/today'
import { fetchWeeklyCalories, type DayCalories } from '../lib/queries/weeklyNutrition'
import { supabase } from '../lib/supabase'
import { useCountUp } from '../composables/useCountUp'
import MacroBar from '../components/MacroBar.vue'
import SkeletonCard from '../components/SkeletonCard.vue'
import WeeklyCalorieChart from '../components/charts/WeeklyCalorieChart.vue'
import MacroDonutChart from '../components/charts/MacroDonutChart.vue'

const auth = useAuthStore()
const totals = ref<DayTotals>({ calories: 0, protein_g: 0, carbs_g: 0, fat_g: 0 })
const loading = ref(true)
const weeklyData = ref<DayCalories[]>([])

type SessionSummary = {
  id: number
  name: string | null
  started_at: string
  setCount: number
}
const todaySessions = ref<SessionSummary[]>([])

function startOfTodayLocalISO(): string {
  const d = new Date()
  d.setHours(0, 0, 0, 0)
  return d.toISOString()
}

async function load() {
  if (!auth.session) return
  loading.value = true
  const [t, weekly] = await Promise.all([
    fetchTodayTotals(auth.session.user.id),
    fetchWeeklyCalories(auth.session.user.id)
  ])
  totals.value = t
  weeklyData.value = weekly

  const since = startOfTodayLocalISO()
  const { data: sessions } = await supabase
    .from('workout_session')
    .select('id, name, started_at')
    .gte('started_at', since)
    .order('started_at', { ascending: false })

  const ids = (sessions ?? []).map((s) => s.id)
  const counts = new Map<number, number>()
  if (ids.length > 0) {
    const { data: logs } = await supabase
      .from('workout_log')
      .select('session_id')
      .in('session_id', ids)
    for (const l of logs ?? []) {
      counts.set(l.session_id, (counts.get(l.session_id) ?? 0) + 1)
    }
  }
  todaySessions.value = (sessions ?? []).map((s) => ({
    id: s.id,
    name: s.name,
    started_at: s.started_at,
    setCount: counts.get(s.id) ?? 0
  }))

  loading.value = false
}

// Ring geometry
const RADIUS = 82
const CIRC = 2 * Math.PI * RADIUS
const ringPct = computed(() => {
  if (!auth.profile) return 0
  return Math.min(1, totals.value.calories / Math.max(1, auth.profile.target_calories))
})
const ringOffset = computed(() => CIRC * (1 - ringPct.value))
const ringOver = computed(() =>
  !!auth.profile && totals.value.calories > auth.profile.target_calories
)

// Count-up for calorie display
const calDisplay = useCountUp(computed(() => Math.round(totals.value.calories)))
const remaining = computed(() => {
  if (!auth.profile) return 0
  return Math.max(0, Math.round(auth.profile.target_calories - totals.value.calories))
})

function fmtTime(iso: string): string {
  return new Date(iso).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
}

onMounted(load)
</script>

<template>
  <template v-if="loading">
    <SkeletonCard :rows="3" style="margin-bottom:.75rem;" />
    <SkeletonCard :rows="2" />
  </template>

  <template v-else-if="auth.profile">
    <!-- Nutrition hero card -->
    <div class="card count-up" style="padding:1.25rem; margin-bottom:.75rem;">
      <!-- Calorie ring -->
      <div style="display:flex; align-items:center; gap:1.25rem; margin-bottom:1.1rem;">
        <div class="cal-ring" style="width:110px; height:110px; flex-shrink:0; position:relative;">
          <svg viewBox="0 0 200 200" width="110" height="110">
            <circle class="cal-ring-track" cx="100" cy="100" :r="RADIUS"
                    fill="none" stroke-width="16" />
            <circle :class="['cal-ring-fill', { 'cal-ring-fill--over': ringOver }]"
                    cx="100" cy="100" :r="RADIUS"
                    fill="none" stroke-width="16" stroke-linecap="round"
                    :stroke-dasharray="CIRC"
                    :stroke-dashoffset="ringOffset" />
          </svg>
          <div style="position:absolute; inset:0; display:flex; flex-direction:column; align-items:center; justify-content:center; text-align:center;">
            <span class="text-num" style="font-size:1.45rem; font-weight:800; line-height:1; letter-spacing:-.03em;">
              {{ calDisplay }}
            </span>
            <span style="font-size:.65rem; color:var(--color-muted); margin-top:.1rem;">kcal</span>
          </div>
        </div>
        <div style="flex:1; min-width:0;">
          <div style="margin-bottom:.2rem;">
            <span style="font-size:1.6rem; font-weight:800; letter-spacing:-.02em; line-height:1;">
              {{ remaining }}
            </span>
            <span style="font-size:.82rem; color:var(--color-muted); margin-left:.3rem;">
              {{ ringOver ? 'over target' : 'kcal left' }}
            </span>
          </div>
          <div style="font-size:.8rem; color:var(--color-muted);">
            Goal: {{ auth.profile.target_calories }} kcal
          </div>
        </div>
      </div>

      <!-- Macro bars -->
      <MacroBar
        label="Protein"
        :current="totals.protein_g"
        :target="auth.profile.target_protein_g"
        unit="g"
        variant="primary"
      />
      <MacroBar
        label="Carbs"
        :current="totals.carbs_g"
        :target="auth.profile.target_carbs_g"
        unit="g"
        variant="warning"
      />
      <MacroBar
        label="Fat"
        :current="totals.fat_g"
        :target="auth.profile.target_fat_g"
        unit="g"
        variant="success"
      />

      <!-- Quick add links -->
      <div class="action-tiles" style="margin-top:.75rem;">
        <RouterLink class="action-tile" :to="{ name: 'log-scan' }">
          <i class="bi bi-upc-scan"></i>
          <span class="action-tile-title">Scan</span>
          <span class="action-tile-sub">Barcode lookup</span>
        </RouterLink>
        <RouterLink class="action-tile" :to="{ name: 'log-quick' }">
          <i class="bi bi-pencil-square"></i>
          <span class="action-tile-title">Quick add</span>
          <span class="action-tile-sub">Manual entry</span>
        </RouterLink>
      </div>
    </div>

    <!-- Macro breakdown donut -->
    <div class="card count-up" style="padding:1.1rem; margin-bottom:.75rem; animation-delay:.05s;">
      <div style="font-size:.78rem; font-weight:700; text-transform:uppercase; letter-spacing:.07em; color:var(--color-muted); margin-bottom:.75rem;">
        Macro breakdown
      </div>
      <MacroDonutChart
        :protein="totals.protein_g"
        :carbs="totals.carbs_g"
        :fat="totals.fat_g"
      />
    </div>

    <!-- Weekly calorie trend -->
    <div class="card count-up" style="padding:1.1rem; margin-bottom:.75rem; animation-delay:.1s;">
      <div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:.75rem;">
        <span style="font-size:.78rem; font-weight:700; text-transform:uppercase; letter-spacing:.07em; color:var(--color-muted);">
          7-day calories
        </span>
        <span style="font-size:.75rem; color:var(--color-muted);">
          <span style="display:inline-block; width:.55rem; height:.55rem; border-radius:50%; background:#f59e0b; margin-right:.25rem;"></span>
          target
        </span>
      </div>
      <WeeklyCalorieChart
        :data="weeklyData"
        :target="auth.profile.target_calories"
      />
    </div>

    <!-- Today's workouts -->
    <div class="card count-up" style="padding:1.1rem; animation-delay:.15s;">
      <div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:.75rem;">
        <span style="display:flex; align-items:center; gap:.4rem; font-weight:700; font-size:.95rem;">
          <i class="bi bi-lightning-charge-fill text-primary"></i>
          Today's training
        </span>
        <RouterLink :to="{ name: 'workout' }"
                    style="font-size:.8rem; color:var(--color-primary); text-decoration:none;">
          View all <i class="bi bi-chevron-right"></i>
        </RouterLink>
      </div>

      <div v-if="todaySessions.length === 0" style="font-size:.85rem; color:var(--color-muted); font-style:italic;">
        No workouts yet today.
        <RouterLink :to="{ name: 'workout' }" style="color:var(--color-primary); text-decoration:none;">
          Start one →
        </RouterLink>
      </div>
      <div v-else>
        <RouterLink
          v-for="s in todaySessions"
          :key="s.id"
          :to="{ name: 'workout-session', params: { id: s.id } }"
          style="display:flex; justify-content:space-between; align-items:center; padding:.5rem 0; border-bottom:1px solid var(--color-border); text-decoration:none; color:inherit;"
        >
          <span>
            <span style="font-weight:600; font-size:.9rem;">{{ s.name || 'Untitled workout' }}</span>
            <span style="font-size:.8rem; color:var(--color-muted); margin-left:.5rem;" class="text-num">
              · {{ s.setCount }} {{ s.setCount === 1 ? 'set' : 'sets' }}
            </span>
          </span>
          <span style="font-size:.8rem; color:var(--color-muted);" class="text-num">{{ fmtTime(s.started_at) }}</span>
        </RouterLink>
      </div>
    </div>
  </template>
</template>
